/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BlockWrapper: typeof import('./src/components/BlockWrapper.vue')['default']
    Button: typeof import('./src/components/blocks/button.vue')['default']
    Divider: typeof import('./src/components/blocks/divider.vue')['default']
    Footer: typeof import('./src/components/blocks/footer.vue')['default']
    Hero: typeof import('./src/components/blocks/hero.vue')['default']
    Image_text: typeof import('./src/components/blocks/image_text.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SendModal: typeof import('./src/components/SendModal.vue')['default']
    Text: typeof import('./src/components/blocks/text.vue')['default']
  }
}
